/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.kelsz.esla;

import features.dashboard;
import features.dividend;
import features.ledger;
import features.member;
import features.serviceCharge;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JPanel;
import ui.Exportable;
import ui.HeaderNav;
import ui.style;

/**
 *
 * @author kelsz-dev
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    private JPanel contentPanel;
    private CardLayout cardLayout;

    public MainFrame() {
    setUndecorated(true);
    initComponents();

    setTitle("ESLA");
    setMinimumSize(new java.awt.Dimension(1100, 700));
    setSize(new java.awt.Dimension(1332, 731));
    getContentPane().removeAll();
    getContentPane().setLayout(new BorderLayout());
    getContentPane().setBackground(style.BACKGROUND);

    HeaderNav nav = new HeaderNav(this);
    JPanel topPanel = new JPanel(new BorderLayout());
    topPanel.setOpaque(false);
    topPanel.add(style.createFrameTitleBar(this, "Main", true), BorderLayout.NORTH);
    topPanel.add(nav, BorderLayout.CENTER);
    getContentPane().add(topPanel, BorderLayout.NORTH);

    cardLayout = new CardLayout();
    contentPanel = new JPanel(cardLayout);
    style.applyPanel(contentPanel);

    contentPanel.add(new dashboard(), "dashboard");
    contentPanel.add(new ledger(), "ledger");
    contentPanel.add(new member(), "member");
    contentPanel.add(new serviceCharge(), "service");
    contentPanel.add(new dividend(), "dividend");

    getContentPane().add(contentPanel, BorderLayout.CENTER);

    cardLayout.show(contentPanel, "dashboard");
    setLocationRelativeTo(null);
}

    public void showPage(String name) {
        System.out.println("Switching to: " + name);
        cardLayout.show(contentPanel, name);
    }

    public void refreshActivePage() {
        System.out.println("Refreshing active page...");
        for (java.awt.Component comp : contentPanel.getComponents()) {
            if (comp.isVisible() && comp instanceof ui.Refreshable) {
                ((ui.Refreshable) comp).refresh();
                break;
            }
        }
    }

    public void exportActivePage(String format) {
        for (java.awt.Component comp : contentPanel.getComponents()) {
            if (comp.isVisible() && comp instanceof Exportable exportable) {
                if ("pdf".equalsIgnoreCase(format)) {
                    exportable.exportToPDF();
                } else if ("excel".equalsIgnoreCase(format)) {
                    exportable.exportToExcel();
                }
                return;
            }
        }
        style.showMessageDialog(this, "Export is not available for this module.");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1332, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
            style.applyGlobalDialogStyle();
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> com.kelsz.esla.Esla.main(args));
    }

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
