/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.kelsz.esla.Database;
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author kelsz-dev
 */
public class LedgerForm extends javax.swing.JPanel {

    /**
     * Creates new form LedgerForm
     */
    private Runnable callback;

    public LedgerForm() {
        initComponents();
        applyStyles();
        populateMemberTypes();
    }

    public void setCallback(Runnable callback) {
        this.callback = callback;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        selectTypeField = new javax.swing.JComboBox<>();
        ledgerCancelButton = new javax.swing.JButton();
        saveLedgerButton = new javax.swing.JButton();
        ledgerDate = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Create Loan");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("Description");

        description.addActionListener(this::descriptionActionPerformed);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel3.setText("Type");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel4.setText("Date");

        selectTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        selectTypeField.addActionListener(this::selectTypeFieldActionPerformed);

        ledgerCancelButton.setText("Cancel");
        ledgerCancelButton.addActionListener(this::ledgerCancelButtonActionPerformed);

        saveLedgerButton.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ledgerCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveLedgerButton))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectTypeField, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ledgerDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ledgerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveLedgerButton)
                    .addComponent(ledgerCancelButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void ledgerCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ledgerCancelButtonActionPerformed
        if (callback != null) {
            callback.run();
        }
    }//GEN-LAST:event_ledgerCancelButtonActionPerformed

    private void saveLedgerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLedgerButtonActionPerformed
        saveLedger();
    }//GEN-LAST:event_saveLedgerButtonActionPerformed

    private void selectTypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectTypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectTypeFieldActionPerformed

    // =========================
    // APPLY STYLES
    // =========================
    private void applyStyles() {
        style.applyPanel(this);
        style.applyTextField(description);
        style.applyComboBox(selectTypeField);
        style.applyButton(saveLedgerButton);
        style.applySecondaryButton(ledgerCancelButton);

        jLabel1.setFont(new Font("Dialog", Font.BOLD, 28));
        jLabel1.setForeground(style.PRIMARY);

        jLabel2.setFont(new Font("Dialog", Font.PLAIN, 15));
        jLabel2.setForeground(Color.DARK_GRAY);

        jLabel3.setFont(new Font("Dialog", Font.PLAIN, 15));
        jLabel3.setForeground(Color.DARK_GRAY);

        jLabel4.setFont(new Font("Dialog", Font.PLAIN, 15));
        jLabel4.setForeground(Color.DARK_GRAY);

        ledgerDate.setFont(new Font("Ubuntu", Font.PLAIN, 15));
        ledgerDate.setDateFormatString("yyyy-MM-dd");
    }

    // =========================
    // POPULATE MEMBER TYPES
    // =========================
    private void populateMemberTypes() {
        try {
            Connection con = Database.getConnection();
            String sql = "SELECT DISTINCT type FROM ledgers ORDER BY type";
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();

            selectTypeField.removeAllItems();

            while (rs.next()) {
                selectTypeField.addItem(rs.getString("type"));
            }

            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // =========================
    // SAVE LEDGER
    // =========================
    private void saveLedger() {
        String desc = description.getText().trim();
        String type = (String) selectTypeField.getSelectedItem();
        Date date = ledgerDate.getDate();

        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a description", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (type == null || type.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please select a type", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (date == null) {
            JOptionPane.showMessageDialog(this, "Please select a date", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            Connection con = Database.getConnection();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String dateStr = sdf.format(date);

            String sql = "INSERT INTO ledgers (description, type, date) VALUES (?, ?, ?)";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, desc);
            ps.setString(2, type);
            ps.setString(3, dateStr);

            ps.executeUpdate();

            ps.close();
            con.close();

            JOptionPane.showMessageDialog(this, "Ledger added successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear form
            description.setText("");
            ledgerDate.setDate(null);

            if (callback != null) {
                callback.run();
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving ledger: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField description;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton ledgerCancelButton;
    private com.toedter.calendar.JDateChooser ledgerDate;
    private javax.swing.JButton saveLedgerButton;
    private javax.swing.JComboBox<String> selectTypeField;
    // End of variables declaration//GEN-END:variables
}
