/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.time.LocalDate;

/**
 *
 * @author kelsz-dev
 */
public class LoanForm extends javax.swing.JDialog {

    private int ledgerId;
    private int memberId;
    private String ledgerType;

    /**
     * Creates new form LoanForm as a modal dialog
     * @param parent The parent frame
     * @param ledgerId The ledger ID
     * @param memberId The member ID
     * @param ledgerType The ledger type
     */
    public LoanForm(java.awt.Frame parent, int ledgerId, int memberId, String ledgerType) {
        super(parent, "Create Loan", true);
        this.ledgerId = ledgerId;
        this.memberId = memberId;
        this.ledgerType = ledgerType;
        initComponents();
        applyStyling();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        pack();
        setLocationRelativeTo(parent);
    }

    private void applyStyling() {
        // Apply dialog content pane styling
        getContentPane().setBackground(java.awt.Color.WHITE);

        // Apply text field styling
        style.applyTextField(formNo);
        style.applyTextField(serviceCharge);
        style.applyTextField(no_of_months);
        style.applyTextField(jTextField1);

        // Apply button styling
        style.applyButton(saveLoanButton);
        style.applyButton(loanCloseButton);

        // Style remarks text area
        remarks.setFont(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 14));
        remarks.setBackground(java.awt.Color.WHITE);
        remarks.setForeground(new java.awt.Color(40, 40, 40));
        remarks.setBorder(javax.swing.BorderFactory.createCompoundBorder(
            new javax.swing.border.LineBorder(style.PRIMARY, 1, true),
            javax.swing.BorderFactory.createEmptyBorder(8, 12, 8, 12)
        ));
        remarks.setLineWrap(true);
        remarks.setWrapStyleWord(true);

        // Style date choosers
        jDateChooser1.setFont(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 14));
        jDateChooser1.setBackground(java.awt.Color.WHITE);
        jDateChooser2.setFont(new java.awt.Font("Ubuntu", java.awt.Font.PLAIN, 14));
        jDateChooser2.setBackground(java.awt.Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        formNo = new javax.swing.JTextField();
        dateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        serviceCharge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        no_of_months = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarks = new javax.swing.JTextArea();
        saveLoanButton = new javax.swing.JButton();
        loanCloseButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Create Loan");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("Form no.");

        formNo.addActionListener(this::formNoActionPerformed);

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dateLabel.setText("Date");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel3.setText("Service charge %");

        jLabel4.setText("No. of months");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel5.setText("Remarks");

        remarks.setColumns(20);
        remarks.setRows(5);
        jScrollPane1.setViewportView(remarks);

        saveLoanButton.setText("Save");

        loanCloseButton.setText("Close");

        jLabel6.setText("Deduction date");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel7.setText("Principal");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serviceCharge)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(formNo, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(no_of_months)
                            .addComponent(jTextField1)
                            .addComponent(dateLabel)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(loanCloseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveLoanButton)))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(dateLabel)
                        .addGap(12, 12, 12)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formNo, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(serviceCharge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(no_of_months, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveLoanButton)
                    .addComponent(loanCloseButton))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNoActionPerformed

    private void saveLoanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLoanButtonActionPerformed
        // Validate form inputs
        if (!validateForm()) {
            return;
        }

        try {
            // Parse form inputs
            java.util.Date selectedDate = jDateChooser2.getDate();
            if (selectedDate == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Please select a date",
                    "Validation Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            LocalDate loanDate = selectedDate.toInstant()
                .atZone(java.time.ZoneId.systemDefault())
                .toLocalDate();

            java.util.Date selectedDeductionDate = jDateChooser1.getDate();
            LocalDate startDeductionDate = null;
            if (selectedDeductionDate != null) {
                startDeductionDate = selectedDeductionDate.toInstant()
                    .atZone(java.time.ZoneId.systemDefault())
                    .toLocalDate();
            }

            Integer formNumber = formNo.getText().trim().isEmpty() ? null : Integer.parseInt(formNo.getText().trim());
            java.math.BigDecimal principal = parseDecimal(jTextField1.getText());
            java.math.BigDecimal serviceChargeValue = parseDecimal(serviceCharge.getText());
            Integer noOfMonths = no_of_months.getText().trim().isEmpty() ? null : Integer.parseInt(no_of_months.getText().trim());
            String remarks = this.remarks.getText();

            // Create loan using LoanService
            services.LoanService loanService = new services.LoanService();
            int loanId = loanService.createLoan(
                ledgerId, memberId, formNumber, loanDate,
                principal, serviceChargeValue, noOfMonths, startDeductionDate, null, remarks
            );

            if (loanId > 0) {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Loan created successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                dispose();
            } else {
                javax.swing.JOptionPane.showMessageDialog(this,
                    "Failed to create loan. Please try again.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter valid numeric values for form number and number of months",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error creating loan: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveLoanButtonActionPerformed

    private void loanCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanCloseButtonActionPerformed
        dispose();
    }//GEN-LAST:event_loanCloseButtonActionPerformed

    /**
     * Validate form inputs
     * @return true if valid, false otherwise
     */
    private boolean validateForm() {
        if (jDateChooser2.getDate() == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please select a date",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        try {
            if (!formNo.getText().trim().isEmpty()) {
                Integer.parseInt(formNo.getText().trim());
            }
            if (!no_of_months.getText().trim().isEmpty()) {
                Integer.parseInt(no_of_months.getText().trim());
            }
            if (!jTextField1.getText().trim().isEmpty()) {
                parseDecimal(jTextField1.getText());
            }
            if (!serviceCharge.getText().trim().isEmpty()) {
                parseDecimal(serviceCharge.getText());
            }
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Please enter valid numeric values",
                "Validation Error",
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * Parse decimal string to BigDecimal
     * @param value The string value to parse
     * @return BigDecimal value or null if empty
     * @throws NumberFormatException if invalid format
     */
    private java.math.BigDecimal parseDecimal(String value) throws NumberFormatException {
        if (value == null || value.trim().isEmpty()) {
            return null;
        }
        // Remove commas and whitespace
        String cleaned = value.replaceAll("[,\\s]", "");
        return new java.math.BigDecimal(cleaned);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField formNo;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loanCloseButton;
    private javax.swing.JTextField no_of_months;
    private javax.swing.JTextArea remarks;
    private javax.swing.JButton saveLoanButton;
    private javax.swing.JTextField serviceCharge;
    // End of variables declaration//GEN-END:variables
}
