/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.kelsz.esla.Database;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;

/**
 *
 * @author kelsz-dev
 */
public class MemberForm extends javax.swing.JPanel {

    private int memberId = -1;
    private boolean isEditMode = false;

    /**
     * Creates new form MemberForm
     */
    public MemberForm() {
        initComponents();
        applyStyles();
    }

    /**
     * Creates new form MemberForm for editing
     */
    public MemberForm(int memberId) {
        this.memberId = memberId;
        this.isEditMode = true;
        initComponents();
        applyStyles();
        jLabel1.setText("Edit Member");
        loadMemberData();
    }

    private void loadMemberData() {
        try {
            Connection con = Database.getConnection();
            String sql = "SELECT * FROM members WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, memberId);
            java.sql.ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                name.setText(rs.getString("name"));
                email.setText(rs.getString("email"));
                phone.setText(rs.getString("phone"));
                formNo3.setText(rs.getString("address"));
                jComboBox1.setSelectedItem(rs.getString("member_type"));
                formNo5.setText(String.valueOf(rs.getInt("premium")));
                java.sql.Date sqlDate = rs.getDate("member_since");
                if (sqlDate != null) {
                    memberSince.setDate(new java.util.Date(sqlDate.getTime()));
                }
            }
            rs.close();
            ps.close();
            con.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        memberSince = new com.toedter.calendar.JDateChooser();
        dateLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        formNo3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        formNo5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Cancel = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Create Member");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("Name");

        name.addActionListener(this::nameActionPerformed);

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        dateLabel.setText("Member Since");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel3.setText("Email");

        email.addActionListener(this::emailActionPerformed);

        phone.addActionListener(this::phoneActionPerformed);

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel4.setText("Phone");

        formNo3.addActionListener(this::formNo3ActionPerformed);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel5.setText("Address");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel6.setText("Member type");

        formNo5.addActionListener(this::formNo5ActionPerformed);

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel7.setText("Premium");

        Cancel.setText("Cancel");
        Cancel.addActionListener(this::CancelActionPerformed);

        saveButton.setText("Save");
        saveButton.addActionListener(this::saveButtonActionPerformed);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "channel 3", "resort", "executive", "consultant", "other" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dateLabel)
                            .addComponent(memberSince, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(formNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel5)
                    .addComponent(formNo3))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(dateLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(memberSince, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(name))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formNo5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formNo3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
        // Close the parent dialog
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_CancelActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void formNo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNo3ActionPerformed

    private void formNo5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formNo5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formNo5ActionPerformed

    private boolean validateForm() {
        if (this.name.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Name is required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            this.name.requestFocus();
            return false;
        }
        if (this.email.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email is required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            this.email.requestFocus();
            return false;
        }
        if (this.phone.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone is required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            this.phone.requestFocus();
            return false;
        }
        if (this.formNo3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address is required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            this.formNo3.requestFocus();
            return false;
        }
        if (this.jComboBox1.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Member type is required", "Validation Error", JOptionPane.ERROR_MESSAGE);
            this.jComboBox1.requestFocus();
            return false;
        }
        return true;
    }

    private void applyStyles() {
        style.applyButton(saveButton);
        style.applySecondaryButton(Cancel);
        style.applyTextField(name);
        style.applyTextField(email);
        style.applyTextField(phone);
        style.applyTextField(formNo3);
        style.applyTextField(formNo5);
        style.applyComboBox(jComboBox1);
        style.applyDateChooserStyle(memberSince);
        
        style.applyModernLabel(jLabel2, false);
        style.applyModernLabel(jLabel3, false);
        style.applyModernLabel(jLabel4, false);
        style.applyModernLabel(jLabel5, false);
        style.applyModernLabel(jLabel6, false);
        style.applyModernLabel(jLabel7, false);
        style.applyModernLabel(dateLabel, false);
        
        style.applyModernLabel(jLabel1, true);
        jLabel1.setVisible(false);
        setBackground(Color.WHITE);
    }

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // Validate form inputs
        if (!validateForm()) {
            return;
        }

        try {
            // Parse form inputs
            String nameText = this.name.getText().trim();
            String emailText = this.email.getText().trim();
            String phoneText = this.phone.getText().trim();
            String addressText = this.formNo3.getText().trim();
            String memberType = (String) this.jComboBox1.getSelectedItem();
            String premiumText = this.formNo5.getText().trim();
            
            java.util.Date selectedDate = this.memberSince.getDate();
            if (selectedDate == null) {
                JOptionPane.showMessageDialog(this,
                    "Please select a member since date",
                    "Validation Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            LocalDate memberSinceDate = selectedDate.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

            int premium = premiumText.isEmpty() ? 0 : Integer.parseInt(premiumText);

            // Insert or update member in database
            Connection con = Database.getConnection();
            
            if (isEditMode) {
                String sql = "UPDATE members SET name=?, email=?, phone=?, address=?, member_type=?, member_since=?, premium=? WHERE id=?";
                PreparedStatement ps = con.prepareStatement(sql);
                
                ps.setString(1, nameText);
                ps.setString(2, emailText);
                ps.setString(3, phoneText);
                ps.setString(4, addressText);
                ps.setString(5, memberType);
                ps.setString(6, memberSinceDate.toString());
                ps.setInt(7, premium);
                ps.setInt(8, memberId);
                
                int rowsAffected = ps.executeUpdate();
                ps.close();
                con.close();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                        "Member updated successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to update member. Please try again.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            } else {
                String sql = "INSERT INTO members (name, email, phone, address, member_type, member_since, premium) VALUES (?, ?, ?, ?, ?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(sql);
                
                ps.setString(1, nameText);
                ps.setString(2, emailText);
                ps.setString(3, phoneText);
                ps.setString(4, addressText);
                ps.setString(5, memberType);
                ps.setString(6, memberSinceDate.toString());
                ps.setInt(7, premium);
                
                int rowsAffected = ps.executeUpdate();
                ps.close();
                con.close();

                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(this,
                        "Member created successfully!",
                        "Success",
                        JOptionPane.INFORMATION_MESSAGE);
                    javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Failed to create member. Please try again.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE);
                }
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Premium must be a valid number",
                "Validation Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error creating member: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JTextField email;
    private javax.swing.JTextField formNo3;
    private javax.swing.JTextField formNo5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private com.toedter.calendar.JDateChooser memberSince;
    private javax.swing.JTextField name;
    private javax.swing.JTextField phone;
    private javax.swing.JButton saveButton;
    // End of variables declaration//GEN-END:variables
}
