/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import com.kelsz.esla.Database;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import services.MemberServiceChargeRefundFormService;

/**
 *
 * @author kelsz-dev
 */
public class ServiceChargeForm extends javax.swing.JPanel {

    private MemberServiceChargeRefundFormService refundFormService;
    /** When non-null, save performs bulk UPDATE for all rows with this description. */
    private String originalDescriptionForEdit;
    /** Set after a successful save or update so the caller can re-select the combo item. */
    private String lastCommittedDescription;

    /**
     * Creates new form ServiceChargeForm (create mode).
     */
    public ServiceChargeForm() {
        initComponents();
        refundFormService = new MemberServiceChargeRefundFormService();
        originalDescriptionForEdit = null;
        saveServiceChargeButton.addActionListener(this::saveServiceChargeButtonActionPerformed);
    }

    /**
     * Edit mode: same form fields, bulk-updates every {@code member_service_charge_refunds} row
     * matching {@code originalDescription}.
     */
    /**
     * Description to select in the parent screen after this dialog closes successfully (may equal the original).
     */
    public String getLastCommittedDescription() {
        return lastCommittedDescription;
    }

    public ServiceChargeForm(String originalDescription, java.sql.Date dateFrom, java.sql.Date dateTo) {
        this();
        this.originalDescriptionForEdit = originalDescription;
        jLabel1.setText("Edit service charge");
        saveServiceChargeButton.setText("Update");
        description.setText(originalDescription);
        if (dateFrom != null) {
            fromDate.setDate(new Date(dateFrom.getTime()));
        }
        if (dateTo != null) {
            toDate.setDate(new Date(dateTo.getTime()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        toDate = new com.toedter.calendar.JDateChooser();
        serviceChargeCancelButton = new javax.swing.JButton();
        saveServiceChargeButton = new javax.swing.JButton();
        fromDate = new com.toedter.calendar.JDateChooser();

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Create Service charge");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel2.setText("Description");

        description.addActionListener(this::descriptionActionPerformed);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel3.setText("From date");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 15)); // NOI18N
        jLabel4.setText("To date");

        serviceChargeCancelButton.setText("Cancel");
        serviceChargeCancelButton.addActionListener(this::serviceChargeCancelButtonActionPerformed);

        saveServiceChargeButton.setText("Save");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(serviceChargeCancelButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveServiceChargeButton))
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(toDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fromDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toDate, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveServiceChargeButton)
                    .addComponent(serviceChargeCancelButton))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveServiceChargeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveServiceChargeButtonActionPerformed
        // Get form values
        String desc = description.getText().trim();
        Date fromDateValue = fromDate.getDate();
        Date toDateValue = toDate.getDate();

        // Validate inputs
        if (desc.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a description", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (fromDateValue == null) {
            JOptionPane.showMessageDialog(this, "Please select a from date", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (toDateValue == null) {
            JOptionPane.showMessageDialog(this, "Please select a to date", "Validation Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Format dates for SQL
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dateFromStr = dateFormat.format(fromDateValue);
        String dateToStr = dateFormat.format(toDateValue);

        try {
            Connection con = Database.getConnection();

            if (originalDescriptionForEdit != null) {
                String updateSql = """
                    UPDATE member_service_charge_refunds
                    SET description = ?, date_from = ?, date_to = ?, updated_at = NOW()
                    WHERE description = ? AND deleted_at IS NULL
                    """;
                PreparedStatement up = con.prepareStatement(updateSql);
                up.setString(1, desc);
                up.setDate(2, new java.sql.Date(fromDateValue.getTime()));
                up.setDate(3, new java.sql.Date(toDateValue.getTime()));
                up.setString(4, originalDescriptionForEdit);
                int rows = up.executeUpdate();
                up.close();
                con.close();

                lastCommittedDescription = desc;
                JOptionPane.showMessageDialog(this,
                    "Updated service charge for " + rows + " refund record(s).",
                    "Success", JOptionPane.INFORMATION_MESSAGE);
                closeHostDialog();
                return;
            }

            // Get all member IDs
            String selectSql = "SELECT id FROM members WHERE deleted_at IS NULL";
            PreparedStatement selectPs = con.prepareStatement(selectSql);
            ResultSet rs = selectPs.executeQuery();

            // Prepare bulk insert statement for refunds
            String insertSql = "INSERT INTO member_service_charge_refunds (member_id, description, date_from, date_to, created_at, updated_at) VALUES (?, ?, ?, ?, NOW(), NOW())";
            PreparedStatement insertPs = con.prepareStatement(insertSql, PreparedStatement.RETURN_GENERATED_KEYS);

            LocalDate dateFromLocal = fromDateValue.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();
            LocalDate dateToLocal = toDateValue.toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDate();

            int refundCount = 0;
            int totalFormsCreated = 0;
            
            while (rs.next()) {
                int memberId = rs.getInt("id");
                insertPs.setInt(1, memberId);
                insertPs.setString(2, desc);
                insertPs.setString(3, dateFromStr);
                insertPs.setString(4, dateToStr);
                insertPs.executeUpdate();
                
                // Get the generated refund ID
                ResultSet generatedKeys = insertPs.getGeneratedKeys();
                if (generatedKeys.next()) {
                    int refundId = generatedKeys.getInt(1);
                    // Create refund forms from loans for this member
                    int formsCreated = refundFormService.bulkInsertFromLoans(memberId, dateFromLocal, dateToLocal, refundId);
                    totalFormsCreated += formsCreated;
                }
                generatedKeys.close();
                refundCount++;
            }

            rs.close();
            selectPs.close();
            insertPs.close();
            con.close();

            lastCommittedDescription = desc;
            JOptionPane.showMessageDialog(this, 
                "Successfully created service charge refunds for " + refundCount + " members\n" +
                "Total refund forms created: " + totalFormsCreated, 
                "Success", JOptionPane.INFORMATION_MESSAGE);

            // Clear form
            description.setText("");
            fromDate.setDate(null);
            toDate.setDate(null);
            closeHostDialog();

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error saving service charge: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveServiceChargeButtonActionPerformed

    private void closeHostDialog() {
        var w = SwingUtilities.getWindowAncestor(this);
        if (w != null) {
            w.dispose();
        }
    }

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void serviceChargeCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serviceChargeCancelButtonActionPerformed
        var w = SwingUtilities.getWindowAncestor(this);
        if (w != null) {
            w.dispose();
        }
    }//GEN-LAST:event_serviceChargeCancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField description;
    private com.toedter.calendar.JDateChooser fromDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton saveServiceChargeButton;
    private javax.swing.JButton serviceChargeCancelButton;
    private com.toedter.calendar.JDateChooser toDate;
    // End of variables declaration//GEN-END:variables
}
